# Generated by Django 4.1.7 on 2023-03-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reserve_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
