# Generated by Django 4.1.7 on 2023-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LIS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="books_issued",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="faculty",
            name="fine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="issuedbook",
            name="fine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="books_issued",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="fine",
            field=models.IntegerField(default=0),
        ),
    ]
