# Generated by Django 4.1.7 on 2023-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
