# Generated by Django 4.1.7 on 2023-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='insti_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='insti_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
