# Generated by Django 4.1.7 on 2023-04-03 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LIS", "0002_faculty_books_issued_faculty_fine_issuedbook_fine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedbook",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reservedbook",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="copies_issued",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reservedbook",
            name="available_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
