# Generated by Django 4.1.7 on 2023-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insti_id', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('isbn', models.CharField(max_length=13)),
                ('reserved_date', models.DateField(auto_now=True)),
                ('available_date', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='student_id',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='book_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='insti_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
