# Generated by Django 4.1.7 on 2023-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0003_alter_book_reserve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reserve_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
