# Generated by Django 4.1.7 on 2023-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0004_alter_book_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reserve_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reserve_id',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
