# Generated by Django 4.1.7 on 2023-03-24 20:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LIS', '0004_pg_rs_ug_remove_faculty_full_name_faculty_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PG',
            new_name='Postgraduate',
        ),
        migrations.RenameModel(
            old_name='RS',
            new_name='ResearchScholar',
        ),
        migrations.RenameModel(
            old_name='UG',
            new_name='Undergraduate',
        ),
    ]
