# Generated by Django 4.1.7 on 2023-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0005_student_books_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books_issued',
        ),
    ]
