# Generated by Django 4.1.7 on 2023-03-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIS', '0006_alter_book_reserve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='last_issue_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_issue_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserve_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserve_id',
        ),
    ]
